export const pessoas = [
    {
        id: 1,
        nome: "Maria",
        sobrenome: "Silva",
        dataNascimento: "1990-03-29",
        sexo: "Feminino",
        grauEscolaridade: "Ensino Superior Completo",
        endereco: "Rua das Flores, 123 - São Paulo, SP",
        optouVT: false,
        salarioAtual: 1518,
        valorPassagem: 22,
        email: "maria.silva@example.com",
        telefone: "(11) 99999-1234",
        cargoAtual: "Analista de RH",
        foto: "banco de dados/img/img1.jpg"
    },
    {
        id: 2,
        nome: "João",
        sobrenome: "Pereira",
        dataNascimento: "1985-07-12",
        sexo: "Masculino",
        grauEscolaridade: "Ensino Médio Completo",
        endereco: "Avenida Paulista, 1000 - São Paulo, SP",
        optouVT: true,
        salarioAtual: 2000,
        valorPassagem: 15,
        email: "joao.pereira@example.com",
        telefone: "(11) 98888-5678",
        cargoAtual: "Motorista",
        foto: "banco de dados/img/img2.jpg"
    },
    {
        id: 3,
        nome: "Ana",
        sobrenome: "Souza",
        dataNascimento: "1995-11-05",
        sexo: "Feminino",
        grauEscolaridade: "Ensino Superior Incompleto",
        endereco: "Rua Central, 250 - Rio de Janeiro, RJ",
        optouVT: true,
        salarioAtual: 1800,
        valorPassagem: 20,
        email: "ana.souza@example.com",
        telefone: "(21) 97777-4567",
        cargoAtual: "Atendente",
        foto: "banco de dados/img/img3.jpeg"
    },
    {
        id: 4,
        nome: "Carlos",
        sobrenome: "Oliveira",
        dataNascimento: "1988-02-14",
        sexo: "Masculino",
        grauEscolaridade: "Ensino Técnico Completo",
        endereco: "Rua da Paz, 45 - Belo Horizonte, MG",
        
        optouVT: false,
        salarioAtual: 2500,
        valorPassagem: 10,
        email: "carlos.oliveira@example.com",
        telefone: "(31) 96666-7890",
        cargoAtual: "Técnico de Informática",
        foto: "banco de dados/img/img4.jpg"
    },
    {
        id: 5,
        nome: "Fernanda",
        sobrenome: "Almeida",
        dataNascimento: "1992-09-22",
        sexo: "Feminino",
        grauEscolaridade: "Ensino Superior Completo",
        endereco: "Rua Primavera, 300 - Curitiba, PR",
        optouVT: true,
        salarioAtual: 3200,
        valorPassagem: 18,
        email: "fernanda.almeida@example.com",
        telefone: "(41) 95555-1122",
        cargoAtual: "Engenheira Civil",
        foto: "banco de dados/img/img5.jpg"
    },
    {
        id: 6,
        nome: "Rafael",
        sobrenome: "Martins",
        dataNascimento: "1983-12-03",
        sexo: "Masculino",
        grauEscolaridade: "Ensino Médio Completo",
        endereco: "Rua das Palmeiras, 85 - Salvador, BA",
        optouVT: false,
        salarioAtual: 1700,
        valorPassagem: 12,
        email: "rafael.martins@example.com",
        telefone: "(71) 94444-3344",
        cargoAtual: "Vendedor",
        foto: "banco de dados/img/img6.png"
    },
    {
        id: 7,
        nome: "Juliana",
        sobrenome: "Costa",
        dataNascimento: "1998-06-18",
        sexo: "Feminino",
        grauEscolaridade: "Ensino Técnico Completo",
        endereco: "Rua do Sol, 90 - Recife, PE",
        optouVT: true,
        salarioAtual: 2100,
        valorPassagem: 16,
        email: "juliana.costa@example.com",
        telefone: "(81) 93333-5566",
        cargoAtual: "Assistente de Marketing",
        foto: "banco de dados/img/img7.jpg"
    },
    {
        id: 8,
        nome: "Pedro",
        sobrenome: "Santos",
        dataNascimento: "1991-05-10",
        sexo: "Masculino",
        grauEscolaridade: "Ensino Superior Completo",
        endereco: "Avenida Atlântica, 500 - Florianópolis, SC",
        optouVT: true,
        salarioAtual: 4000,
        valorPassagem: 25,
        email: "pedro.santos@example.com",
        telefone: "(48) 92222-7788",
        cargoAtual: "Desenvolvedor Full Stack",
        foto: "banco de dados/img/img8.jpeg"
    }
];
